image:
  file: .gitpod.dockerfile

tasks:
  - init: . ${GITPOD_REPO_ROOT}/.vscode/init_tasks.sh
    command: /home/gitpod/.pg_ctl/bin/pg_start > /dev/null

  # Install Stripe CLI during workspace initialization
  - before: |
      curl -L -o stripe.tar.gz https://github.com/stripe/stripe-cli/releases/download/v1.23.3/stripe_1.23.3_linux_x86_64.tar.gz
      tar -xvzf stripe.tar.gz
      sudo mv stripe /usr/local/bin/
      stripe version
    command: echo "Stripe CLI installed and ready"

  - command: . ${GITPOD_REPO_ROOT}/.vscode/uptime.sh &

vscode:
  extensions: 
    - esbenp.prettier-vscode
    - eventyret.bootstrap-4-cdn-snippet
    - formulahendry.auto-close-tag
    - github.vscode-pull-request-github
    - gitpod.gitpod-remote-ssh
    - gitpod.gitpod-desktop
    - junstyle.vscode-django-support
    - matt-rudge.auto-open-preview-panel
    - ms-python.black-formatter
    - ms-python.debugpy
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-python.flake8
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - ms-toolsai.vscode-jupyter-cell-tags
    - ms-toolsai.vscode-jupyter-slideshow
    - redhat.vscode-yaml
    - vivaxy.vscode-conventional-commits
    - numso.prettier-standard-vscode
    - aeschli.vscode-css-formatter